### ISSUE TITLE
MCP25xxfd driver port

### ISSUE THREAD

**Issue by kjngineering** [marckleinebudde/linux#2]
Hey @marckleinebudde,

Is this appropriate branch to backport to my 5.3.x mainline?

Is the sun8i driver modification just clocking to make it work for the MCP application or is there more here to understand (e.g. that might effect my display on the same bus?).

Alas nothing commercial yet, just playing with my car waiting for covid to be over. But if it works it might have some opportunity. :)

**Comment by marckleinebudde** [comment]
The appropriate branch would be the latest `sunxi`.

The spi patches fix the clock and speed up the driver. So your display would benefit from this. :smiley:

**Comment by kjngineering** [comment]
I already had my sunxi SPI running to the display at 60MHz - or does it just help with more dividers? or something else?

What is the deal with the msperl mcp25xxfd drivers? Are they no longer developed? I saw they were submitted to linux-can mailing list to merge to mainline sometime ago and went through several revisions, but never accepted?

Is the intention to finish the development in this branch and mainline the result (both spi patch and MCP driver?)

**Comment by marckleinebudde** [comment]
> I already had my sunxi SPI running to the display at 60MHz - or does it just help with more dividers? or something else?

The sunxi spi driver is broken, it gives you a higher SPI clock than you request.

> What is the deal with the msperl mcp25xxfd drivers?

It's not that stable and development has stalled.

> Are they no longer developed?

From my point of view the driver has a bad design so I decided to rewrite it.

> I saw they were submitted to linux-can mailing list to merge to mainline sometime ago and went through several revisions, but never accepted?

ACK

> Is the intention to finish the development in this branch and mainline the result (both spi patch and MCP driver?)

Yes, as time allows.

**Comment by kjngineering** [comment]
If I am building on sunxi 5.4.45 would you still recommend your sunxi 4.19 branch?

**Comment by kjngineering** [comment]
Hi Marc,

I tried building sunxi - 4.19 - 46 branch against 5.4.45:

```
rivers/net/can/spi/mcp25xxfd/mcp25xxfd-core.c: In function ‘mcp25xxfd_tx_ring_init_tx_obj’:
drivers/net/can/spi/mcp25xxfd/mcp25xxfd-core.c:314:23: error: request for member ‘value’ in something not a structure or union
  xfer->cs_change_delay.value = 0;
                       ^
drivers/net/can/spi/mcp25xxfd/mcp25xxfd-core.c:315:23: error: request for member ‘unit’ in something not a structure or union
  xfer->cs_change_delay.unit = SPI_DELAY_UNIT_NSECS;
                       ^
drivers/net/can/spi/mcp25xxfd/mcp25xxfd-core.c: In function ‘mcp25xxfd_probe’:
drivers/net/can/spi/mcp25xxfd/mcp25xxfd-core.c:2846:8: error: implicit declaration of function ‘can_rx_offload_add_manual’; did you mean ‘can_rx_offload_add_fifo’? [-Werror=implicit-function-declaration]
  err = can_rx_offload_add_manual(ndev, &priv->offload,
        ^~~~~~~~~~~~~~~~~~~~~~~~~
        can_rx_offload_add_fifo
cc1: some warnings being treated as errors
```

I guess this is due to kernel changes between 4.19 and 5.4.45 versions. can I try the rpi - 5.7 branch or does the sunxi version have sunxi specific changes (other than say the SPI patch -- which I am patching seperately)

Edit: I have tried various other build versions (rpi 5.7-46, rpi-5.6-41, sunxi-4.19-41) and they all fail at the same error.

Thanks

**Comment by marckleinebudde** [comment]
As we've discussed things via mail on the [linux-can mailing list](https://lore.kernel.org/r/61a5dd2e-7c80-3d33-34ef-7aaa4e8f2a7f@pengutronix.de), can we close this issue?

**Comment by kjngineering** [comment]
Yes - I believe the issues here are resolved and discussed clearly on the mailing list along with the appropriate patches for a backport. This can be closed.
