### ISSUE TITLE
can0 & can1 interfaces are up automatically - but why?

### ISSUE THREAD

**Issue by hanlectin** [marckleinebudde/linux#6]
Hi and thanks a lot for the kernel with the MCP25xxFD

I successfully compiled and activated a version of this kernel around june 2020.
everything was/is working fine!

however, something bothers me now and I can't find the reason for the current behavior:
I have two CANs and I'm using:
```
dtoverlay=mcp25xxfd-spi0-1,oscillator=40000000,interrupt=05
dtoverlay=mcp25xxfd-spi0-0,oscillator=40000000,interrupt=25
```
now the strange thing is, just by adding the above lines to /boot/config.txt I automatically get the interfaces can0 and can1
*) there is no entry for can0 or can1 in /etc/network/interfaces
*) I also have no service in /lib/systemd/system/ that calls "ip link set can1 up type can bitrate 500000" or (similar)

who/what starts my can interfaces?

although it's quite convenient that the interfaces "work out of the box", I want can1 to operate with bitrate=250000
I could - and have for testing - create a service that executes (with some seconds delay) "ifconfig can1 down" followed by "ip link set can1 up ..."
...but there must be another/simpler way, right?

maybe I really miss something that I added a few month ago - but I can't remember at all and I have also searched the whole filesystem for entries like "can1" "500000" or "500k"... but I just can't find anything that would bring up can0/can1 

below are the dmesg entries for the interfaces:

```
> dmesg | grep can0
[    4.583718] mcp25xxfd spi0.0 can0: MCP2518FD rev0.0 (-RX_INT -MAB_NO_WARN +CRC_REG +CRC_RX +CRC_TX +ECC -HD m:20.00MHz r:18.50MHz e:17.85MHz) successfully initialized.
[   11.934597] IPv6: ADDRCONF(NETDEV_UP): can0: link is not ready
[   11.934649] IPv6: ADDRCONF(NETDEV_CHANGE): can0: link becomes ready
```

```
> dmesg | grep can1
[    4.598432] mcp25xxfd spi0.1 can1: MCP2518FD rev0.0 (-RX_INT -MAB_NO_WARN +CRC_REG +CRC_RX +CRC_TX +ECC -HD m:20.00MHz r:18.50MHz e:17.85MHz) successfully initialized.
[   11.999777] IPv6: ADDRCONF(NETDEV_UP): can1: link is not ready
[   12.967251] IPv6: ADDRCONF(NETDEV_CHANGE): can1: link becomes ready
```

thanks very much,
Hannes

**Comment by intx82** [comment]
What about NetworkManager?

**Comment by hanlectin** [comment]
> What about NetworkManager?

no - not installed:
```
> sudo systemctl status NetworkManager.service
Unit NetworkManager.service could not be found.
```
```
> dpkg -s networkmanager
dpkg-query: package 'networkmanager' is not installed and no information is available
```

**Comment by hanlectin** [comment]
aarrgghh - solved!
I recently also installed CodeSys (Software PCL) on this raspi. and played with can...
So I configured can0 and can1 in CodeSys - which brings up can0 and can1 during boot :(((
