### ISSUE TITLE
multiple RX FIFOs

### ISSUE THREAD

**Issue by Skypodo** [marckleinebudde/linux#8]
I noticed that the driver uses 1 RX FIFO per default, due to [struct mcp25xxfd_rx_ring *rx[1];](https://github.com/marckleinebudde/linux/blob/v4.19-rpi/mcp25xxfd-20200429-46/drivers/net/can/spi/mcp25xxfd/mcp25xxfd.h#L670). Is there a reason for that? Increasing this value to have more FIFOs available seams to result in worse performance during high bus load.

**Comment by marckleinebudde** [comment]
FYI: fixed with https://github.com/marckleinebudde/linux/commit/9263c2e92be95a7bba009d760420170f808c2243
